git:
  depth: 9999999

sudo: required

language: go

go:
  - 1.15.x

services:
  - docker

script:
  - script/docker/build

after_script:
  - script/ci/genauthors
  - script/ci/can-release && script/ci/release

env:
  global:
    - "PATH=$HOME/gopath/bin:$PATH"
    - secure: U6EwNYogDn4Nzussq2GTpcSdjtPF0w/qoFYo9wgOdR6+YMq5G8eK0Y+7Z9zBY9jlEYPTKxZb/a/flX3LtkmkGUrVQYJSTJC/jpYsBhi105PebMY2Hvc2qsLJdy8n23t8/nxJLIOhRUo2HdSSX2TmiCelcOjBVHBrc1sPm9/8/9efdkNA0yfyYqE9MoK4qoztMLRUKiQpQtxLXUXW1Qz+kmmoW+CbNMuImL6R2Gv4JcHmLgu43MfdCcTo72oGLjC9A3lyvE3r/SwaQ3xEjJviRmE0db4/FBEt99iLxak4vxhfBYstZ/9eeC8yFAkb76Zk3boRVYNj3T/NALlJZt9t/2aDmIVnRGpZvtOmOhVr33fuB0RNt50LvtUObOxCc+ohHTpA89UNHJuMsPkGoqqoIwq2hh9GMgXjsudonDK67b9DeK0bFna8nuzlEn7gJWsSvxVi4VuX82fibeRNtczQ+sD8rQgMsG+Eyx8bV0rRcieKsEZ+kg4EOxm7WqJ319Zg4PHziY3kt/RBgFL6kvtwMWVRnAYYr09HE3D8zpAfD+3rMQhPXXCuc42McFr5Ybl9bRvufKiZfxdpqEGECO7hwRO8Ivs77x9LorFeSg0FvNORJWa5y+FX4DWvxinLquEd+S3m6Nv6d61uTotQXatbWqSB3i2E0i1KliEGgT7aez0=
